<div style="margin-top: 150px; margin-bottom:100px;">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header">Login</div>
                  <div class="card-body">
                <form method="POST" action="<?=App::config('url')?>admin/update" enctype="multipart/form-data">
                <div class="form-row">
                <div class="form-group col-md-16">
                  <label for="name">Name</label>
                  <input type="text"  id="name" name="name" value="<?=$game->name?>" placeholder="Game name">
                </div>
                <div class="form-group col-md-16">
                  <label for="price">Price</label>
                  <input type="text" id="price" value="<?=$game->price?>" name="price">
                </div>
              </div>
              <div class="form-group col-md-16">
                <label for="description">Description</label>
                <input type="text" id="description" value="<?=$game->description?>" name="description" placeholder="Enter game description">
              </div>
              <div class="form-group col-md-16">
                <label for="quantity">Quantity</label>
                <input type="text" id="quantity" value="<?=$game->quantity?>" name="quantity">
              </div>
              <div class="form-row">
                <div class="form-group col-md-16">
                  <label for="memory_required">Required Free Space</label>
                  <input type="text" id="memory_required" value="<?=$game->memory_required?>" name="memory_required">
                </div>
                <div class="form-group col-md-4" style="margin-top:20px;">
                    <fieldset>
                      <legend>Console</legend>
                      <input style="margin:2px;" type="radio"
                      <?php echo !$game->console ? 'checked="checked"' : '';?>
                      name="console" value="PC" id="pc"><label for="pc">PC</label>

                      <input style="margin:2px;" type="radio" 
                      <?php echo !$game->console ? 'checked="checked"' : '';?> name="console" value="PS4" id="ps4"><label for="ps4">PS4</label>

                      <input style="margin:2px;" type="radio" checked="checked"
                      <?php echo $game->console ? 'checked="checked"' : ';'?> name="console" value="Both" id="Both"><label for="both">Both</label>          
                    </fieldset>
                </div  class="form-group col-md-16">
                    <label for="image">Image</label>
                    <input type="file" name="image" value="<?=$game->image?>" id="image">
                    <?php if(isset($game->image)){ $_SESSION['image'] = $game->image; }?>
                <div>
                </div>
              </div>
              <div style="margin-top:20px;">
              <button type="submit" class="btn btn-primary">Update</button>
              <a href="<?=App::config('url')?>admin/index" class="btn btn-danger">Go Back</a>
              </div>
              <div style="margin-top:10px">
              <?=$message?>
              <input type="hidden" name="id" value="<?=$game->id?>">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
