<div class="container">
    <div style="margin-top:150px; margin-bottom:200px;">
        <div class="grix-x">
            <div class="cell large-6">
                <h1 style="font-size: 2rem; text-align:center;">CHANGE YOUR GAME COLLECTION</h1>
            </div>
        <div class="cell large-6" style="text-align:right; margin-top:20px;">
        <a href="<?=App::config('url')?>admin/add" class="btn btn-primary">
    Add a new game.
    </a>
    </div>
</div>
        <table class="table table-bordered" style="margin-top:15px;">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Descripton</th>
                    <th>Quantity</th>
                    <th>Required Memory</th>
                    <th>Console</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($games as $game):?>
                    <tr>
                        <td><?=$game->name?></td>
                        <td style="text-align: right;"><?=$game->price?></td>
                        <td style="max-width:200px;"><?=$game->description?></td>
                        <td style="text-align:center"><?=$game->quantity?></td>
                        <td style="text-align:center"><?=$game->memory_required?> GB</td>
                        <td style="text-align:center"><?=$game->console?></td>
                        <td><img class="adminimg" src="<?=App::config('url')?>public/img/order/<?=$game->image?>"></td>
                        <td>
                            <a href="<?=App::config('url')?>admin/change?id=<?=$game->id?>"> <i title="Change" class="fas fa-pencil-alt"></i></a>
                            <a onclick="return confirm('Are you sure you want to delete &#34;<?=$game->name?>&#34;?');"
                             href="<?=App::config('url')?>admin/delete?id=<?=$game->id?>"><i title="Delete" style="color:red; margin-left:10px;" class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>