<div class="container" style="margin-top: 150px;">
            <div class="row">
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <a href="#!"><img class="card-img-top" src="<?=App::config('url')?>public/img/shake.jpg" alt="..." /></a>
                        <div class="card-body">
                            <div class="small text-muted">July 22, 2021</div>
                            <h2 class="card-title">CyberX buys 100 latest games</h2>
                            <p class="card-text">In the past year the Cyberx store bought approximately 80 games that were made the same year.
                                                 But this year, they bought more then 100 of the latest games right at the start of the year.</p>
                            <a class="btn btn-primary" href="#!">Read more →</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="<?=App::config('url')?>public/img/store1.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">June 2, 2021</div>
                                    <h2 class="card-title h4">Hill of new games</h2>
                                    <p class="card-text">In addition to buying a store to sell games, we also bought a lot of new games 
                                                         that most stores don’t have for sale. The oldest games we keep are from 2015.
                                                         We expect many more new games in the next few months.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="<?=App::config('url')?>public/img/newppl.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">January 11, 2021</div>
                                    <h2 class="card-title h4">New employees</h2>
                                    <p class="card-text">The year 2020 was very successful for CyberX Games. In 2020, we employed over 100 people in 10 different cities.
                                                         Our plan in the future is to open 10 more stores in 5 other cities in the Republic of Croatia and move our stores outside Croatia.
                                                         We hope to do that by the end of this year.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="<?=App::config('url')?>public/img/store.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">May 20, 2021</div>
                                    <h2 class="card-title h4">Massive giveaway</h2>
                                    <p class="card-text">The Republic of Croatia has helped us collect a lot of new PC games. As a gift, 
                                                         we received two hundred new and one hundred older PC games. 
                                                         We give away 100 games.
                                                         All you have to do is log in to our new website.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="<?=App::config('url')?>public/img/open.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">December 12, 2020</div>
                                    <h2 class="card-title h4">Shops opening all over Croatia</h2>
                                    <p class="card-text">After a year of selling games online, and having only one store in our home town Osijek, 
                                        we are pleased to announce that we are opening stores in 7 more Croatian cityes.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
                            <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
                            <li class="page-item"><a class="page-link" href="#!">2</a></li>
                            <li class="page-item"><a class="page-link" href="#!">3</a></li>
                            <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                            <li class="page-item"><a class="page-link" href="#!">15</a></li>
                            <li class="page-item"><a class="page-link" href="#!">Older</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="What are you searching for?" aria-label="What are you searching for?" aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">Web Design</a></li>
                                        <li><a href="#!">HTML</a></li>
                                        <li><a href="#!">Freebies</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>
        </div>