<div class="masthead  text-center">
        <div class="container d-flex align-items-center flex-column"> 
            <br><br><br><br>
            <h1 class="masthead-heading text-uppercase mb-0"><?=App::config('appName')?></h1>
            <div class="divider-custom divider-light"></div>
            <p class="masthead-subheading font-weight-light mb-0">Where the magic happens</p>
            </div>
        <br>
    <div>
        <a href="<?=App::config('url')?>index/register" class="btn btn-secondary btn-lg">Register</a>
    </div>
</div>