<br><br><br>
<div class="row" style="margin-top: 100px;">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Login</div>
                        <div class="card-body">
                          <form class="log-in-form" method="POST" 
                                action="<?=App::config('url')?>index/authorisation">
                                <div class="form-group row">
                                    <label for="full_name" class="col-md-4 col-form-label text-md-right">User name</label>
                                    <div class="col-md-6">
                                        <input type="text" placeholder="Enter user name" id="username" class="form-control" value="<?=$email?>" name="email">
                                        <small id="emailHelp" class="form-text" style="color:red">Username: admin@edunova.hr</small><br>
                                        <small id="emailHelp" class="form-text" style="color:blue">Username: oper@edunova.hr</small>
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <label for="email_address" class="col-md-4 col-form-label text-md-right">Password</label>
                                    <div class="col-md-6">
                                        <input type="password" id="password" placeholder="Enter Password" class="form-control" name="password">
                                        <small id="emailHelp" class="form-text" style="color:red">Password: a</small>
                                    </div>
                                </div>
                                <br>
                                <?=$message?>
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                        Login
                                        </button>
                                        <p><a href="register.php">Don't have an account?</a></p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>