<br><br><br>
<div class="row" style="margin-top: 100px; margin-bottom:100px;">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Login</div>
                        <div class="card-body">
                          <form class="log-in-form" method="POST" 
                                action="<?=App::config('url')?>index/registration">
                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                                    <div class="col-md-6">
                                        <input type="text" placeholder="Enter user name" id="username" class="form-control" value="<?=$name?>" name="name">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <label for="surname" class="col-md-4 col-form-label text-md-right">Surname</label>
                                    <div class="col-md-6">
                                        <input type="text" id="surname" placeholder="Enter Surname" class="form-control" value="<?=$surname?>" name="surname">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
                                    <div class="col-md-6">
                                        <input type="email" id="email" placeholder="Enter Email" class="form-control" value="<?=$email?>" name="email">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                                    <div class="col-md-6">
                                        <input type="password" id="password" placeholder="Enter Password" class="form-control" name="password">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <label for="confirmPassword" class="col-md-4 col-form-label text-md-right">Confirm Password</label>
                                    <div class="col-md-6">
                                        <input type="password" id="password" placeholder="Enter Password" class="form-control" name="confirmPassword">
                                    </div>
                                </div>
                                <br>
                                <?=$message?>
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                        Register
                                        </button>
                                        <p><a href="<?=App::config('url')?>index/login">Already have an acconut?</a></p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>