<!DOCTYPE html>
<html lang="en">
<head>
    <?php include_once 'templates/head.phtml'?>
</head>
<body>
    <div class="grid-container">
        <?php include_once 'templates/menu.phtml'?>
            <div class="callout" id="program">
                <?=$content?>
            </div>
            <?php include_once 'templates/footer.phtml'?>
    </div>
    <?php include_once 'templates/scripts.phtml'?>
</body>
</html>