<div class="container">
    <div style="margin-top:150px; margin-bottom:200px;">
        <div class="grix-x">
            <div class="cell large-6">
                <h1 style="font-size: 2rem; text-align:center;"><?=$message?></h1>
            </div>
        </div>
        <?php if(!empty($_SESSION['cart'])): ?>
        <?php $total=0;?>
        <table class="table table-bordered" style="margin-top:15px;">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Descripton</th>
                    <th>Quantity</th>
                    <th>Required Memory</th>
                    <th>Console</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                
                <?php foreach($_SESSION['cart'] as $game=>$value):?>
                    <tr>
                    <td><img class="adminimg" src="<?=App::config('url')?>public/img/order/<?=$value['image']?>"></td>
                        <td style="min-width:150px;"><?=$value['name']?></td>
                        <td style="text-align: right;min-width:150px; text-align:center"><?=$value['price']?>$</td>
                        <td><?=$value['description']?></td>
                        <td style="min-width:140px; text-align:center;"><?=$value['quantity']?></td>
                        <td style="text-align:center"><?=$value['memory_required']?> GB</td>
                        <td style="text-align:center"><?=$value['console']?></td>
                        <td style="min-width:80px; text-align:center">
                            <a href="<?=App::config('url')?>games/updateCart"> <i title="Update" class="fas fa-pencil-alt"></i></a>
                            <a onclick="return confirm('Are you sure you want to remove &#34;<?=$value['name']?>&#34; from the cart?');"
                             href="<?=App::config('url')?>games/remove?id=<?=$value['id']?>"><i title="Remove" style="color:red; margin-left:10px;" class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    <?php $total = $total + $value['quantity'] * $value['price']; ?>
                    <?php endforeach;?>
                    
                    <tr>
                            <td style="text-align:center;"><a class="btn btn-success" href="<?=App::config('url')?>games/checkout">Checkout</a></td>
                            <td style="text-align:center;"><a class="btn btn-danger" onclick="return confirm('Are you sure you want to clear the cart?');" href="<?=App::config('url')?>games/clear">Clear</a></td>
                            <td colspan="5" align="right">Total</td>
                            <td style="min-width:100px;" class="total" colspan="2"><b><?=$total?>$</b>
                            </td>
                    </tr>
            </tbody>
        </table>
        <?php endif;?>
    </div>
</div>