<div style="margin-top: 150px; margin-bottom:100px;">
<div class="container mt- px-5">
    <div class="mb-4">
        <h2>Confirm order and pay</h2> <span>please make the payment, after that you can enjoy all the features and benefits.</span>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="<?=App::config('url')?>games/pay" method="POST">
            <div class="card p-3">
                <h6 class="text-uppercase">Payment details</h6>
                <div class="inputbox mt-3"> <input type="text" name="name" class="form-control" placeholder="John" required="required"> <span>Name on card</span> </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="inputbox mt-3 mr-2"> <input type="number" name="card" class="form-control" placeholder="XXXX XXXX XXXX XXXX" required="required"> <i class="fa fa-credit-card"></i> <span>Card Number</span> </div>
                    </div>
                    <div class="col-md-6">
                        <div class="d-flex flex-row">
                            <div class="inputbox mt-3 mr-2"> <input type="text" name="expiry" placeholder="01/22" class="form-control" required="required"> <span>Expiry</span> </div>
                            <div class="inputbox mt-3 mr-2"> <input type="text" name="cvv" class="form-control" required="required"> <span>CVV</span> </div>
                        </div>
                    </div>
                </div>
                <div class="mt-4 mb-4">
                    <h6 class="text-uppercase">Billing Address</h6>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <div class="inputbox mt-3 mr-2"> <input type="text" name="address" class="form-control" required="required"> <span>Street Address</span> </div>
                        </div>
                        <div class="col-md-6">
                            <div class="inputbox mt-3 mr-2"> <input type="text" name="city" class="form-control" required="required"> <span>City</span> </div>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <div class="inputbox mt-3 mr-2"> <input type="number" name="zipcode" class="form-control" required="required"> <span>Zip code</span> </div>
                        </div>
                    </div>
                </div>
                <?php if(isset($message)){echo $message;}?>
            </div>
            <?php $total = $_SESSION['total'];?>
            <div class="mt-4 mb-4 d-flex justify-content-between"><button  type="submit"class="btn btn-success px-5">Pay <?=$total?></button><a href="<?=App::config('url')?>games/cart" class="btn btn-danger">Back</a></div>
            <div>
                
            </div>
        </div>
      </form>
    </div>
</div>
</div>