<nav aria-label="...">
  <ul class="pagination">
    <?php if($page!=1): ?>
      <li class="page-item">
      <a class="page-link" href="<?=App::config('url')?>games/index?page=<?php echo $page-1?>" tabindex="-1">Previous</a>
    </li>
    <li class="page-item"><a class="page-link" href="<?=App::config('url')?>games/index?page=<?php echo $page-1?>"><?=$page-1?></a></li>
    <?php else : ?>
      <li class="page-item"><a class="page-link">Previous</a></li>
      <li class="page-item"><a class="page-link">...</a></li>
    <?php endif; ?>
    <li class="page-item active">
      <a class="page-link" href="<?=App::config('url')?>games/index?page=<?=$page?>"><?=$page?> <span class="sr-only"></span></a>
    </li>
    <?php if($page != $pageCount): ?>
    <li class="page-item"><a class="page-link" href="<?=App::config('url')?>games/index?page=<?php echo $page+1?>"><?=$page+1?></a></li>
    <li class="page-item">
      <a class="page-link" href="<?=App::config('url')?>games/index?page=<?php echo $page+1?>">Next</a>
    </li>
    <?php else : ?>
      <li class="page-item"><a class="page-link">...</a></li>
      <li class="page-item"><a class="page-link">Next</a></li>
    <?php endif; ?>
  </ul>
</nav>