<div style="margin-top:90px;">
<header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-4">
                    <h1 class="fw-bolder">Welcome to <?=App::config('appName')?></h1>
                    <h2 class="lead mb-0"><?=Request::user()?></h2>
                </div>
            </div>
        </header>
        <div class="smaller">
            <section class="py-5">
                <div class="container px-5">
                    <h1 class="fw-bolder fs-5 mb-4">Upcoming game</h1>
                    <div class="card">
                        <a href="#!"><img class="card-img-top" src="<?=App::config('url')?>public/img/order/codvan.jpg" alt="..." /></a>
                        <div class="card-body">
                            <div class="small text-muted">January 1, 2021</div>
                            <h2 class="card-title">Call of Duty: Vanguard</h2>
                            <p class="card-text">Call of Duty: Vanguard is an upcoming 2021 first-person shooter video game developed by Sledgehammer Games and published by Activision.</p>
                            <a class="btn btn-danger" href="#!">COMING SOON</a>
                        </div>
                    </div>
                </div>
            </section>
        </div>
            <section class="py-5">
                    <div class="container px-5">
                        <h2 class="fw-bolder fs-5 mb-4" style="text-align: center;">Newest games</h2>
                        <div class="row gx-5">
                            <?php foreach($games as $game):?>
                        <div class="col-md-4">
                        <h3><?=$game->name?></h3>
                        <div class="card mb-4 box-shadow">
                            <img class="games-img" src="<?=App::config('url')?>public/img/order/<?=$game->image?>" alt="Card image cap">
                            <div class="card-body">
                            <p class="card-text">Price: <?=$game->price?>$</p>
                            <p class="card-text">Console: <?=$game->console?></p>
                            <p class="card-text">Memory required: <?=$game->memory_required?> GB</p>
                            <p class="card-text"><?=$game->description?></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <form action="<?=App::config('url')?>games/add" method="POST">
                                    <input type="hidden" name="id" value="<?=$game->id?>">
                                    <input style="margin:10px;" type="number" name="quantity" value="1" min="1" max="<?=$game->quantity?>" placeholder="Quantity" required>
                                    <button type="submit" name="add" class="btn btn-primary">Add to Cart</button> 
                                </form>
                                <?php if(Request::isAdmin()): ?>
                                <a href="<?=App::config('url')?>games/change?id=<?=$game->id?>"> <i title="Change" class="fas fa-2x fa-pencil-alt"></i></a>
                                <?php endif;?>
                            </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach;?>
            </section>
    </div>