<div style="margin-top:90px;">
<header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-4">
                    <h1 class="fw-bolder">Welcome to <?=App::config('appName')?></h1>
                    <h2 class="lead mb-0"><?=Request::user()?></h2>
                </div>
            </div>
        </header>
        <div class="smaller">
            <section class="py-5">
                <div class="container px-5">
                    <h1 class="fw-bolder fs-5 mb-4">Newest game</h1>
                    <div class="card">
                        <a href="#!"><img class="card-img-top" src="<?=App::config('url')?>public/img/codvan.jpg" alt="..." /></a>
                        <div class="card-body">
                            <div class="small text-muted">January 1, 2021</div>
                            <h2 class="card-title">Call of Duty: Vanguard</h2>
                            <p class="card-text">Call of Duty: Vanguard is an upcoming 2021 first-person shooter video game developed by Sledgehammer Games and published by Activision.</p>
                            <a class="btn btn-danger" href="#!">PRE-ORDER</a>
                        </div>
                    </div>
                </div>
            </section>
        </div>
            <section class="py-5">
                <div class="container px-5">
                    <h2 class="fw-bolder fs-5 mb-4" style="text-align: center;">Upcoming games</h2>
                    <div class="row gx-5">
                        <div class="col-lg-4 mb-5">
                            <div class="card h-100 shadow border-0">
                                <img class="card-img-top" src="<?=App::config('url')?>public/img/acval.jpg" alt="..." />
                                <div class="card-body p-4">
                                    <div class="badge bg-primary bg-gradient rounded-pill mb-2">Game</div>
                                    <a class="text-decoration-none link-dark stretched-link" href="#!"><div class="h5 card-title mb-3">Assassin's Creed Valhalla</div></a>
                                    <p class="card-text mb-0">Assassin's Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin's Creed series, and the successor to 2018's Assassin's Creed Odyssey.</p>
                                </div>
                                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                                    <div class="d-flex align-items-end justify-content-between">
                                        <div class="d-flex align-items-center">
                                            <div class="small">
                                                <div class="fw-bold"><a class="btn btn-primary" href="#!">Add to cart</a></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 mb-5">
                            <div class="card h-100 shadow border-0">
                                <img class="card-img-top" src="<?=App::config('url')?>public/img/rd2.jpg" alt="..." />
                                <div class="card-body p-4">
                                    <div class="badge bg-primary bg-gradient rounded-pill mb-2">Game</div>
                                    <a class="text-decoration-none link-dark stretched-link" href="#!"><div class="h5 card-title mb-3">Red Dead Redemption 2</div></a>
                                    <p class="card-text mb-0">Red Dead Redemption 2 is a 2018 action-adventure game developed and published by Rockstar Games. The game is the third entry in the Red Dead series and is a prequel to the 2010 game Red Dead Redemption.</p>
                                </div>
                                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                                    <div class="d-flex align-items-end justify-content-between">
                                        <div class="d-flex align-items-center">
                                            <div class="small">
                                            <a class="btn btn-primary" href="#!">Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 mb-5">
                            <div class="card h-100 shadow border-0">
                                <img class="card-img-top" src="<?=App::config('url')?>public/img/village.jpg" alt="..." />
                                <div class="card-body p-4">
                                    <div class="badge bg-primary bg-gradient rounded-pill mb-2">Game</div>
                                    <a class="text-decoration-none link-dark stretched-link" href="#!"><div class="h5 card-title mb-3">Resident Evil Village</div></a>
                                    <p class="card-text mb-0">Resident Evil Village is a 2021 first-person survival horror game developed and published by Capcom. It is the sequel to Resident Evil 7: Biohazard</p>
                                </div>
                                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                                    <div class="d-flex align-items-end justify-content-between">
                                        <div class="d-flex align-items-center">
                                            <div class="small">
                                            <a class="btn btn-primary" href="#!">Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    </div>