<footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            First Street 52a
                            <br />
                        </p>
                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-instagram"></i></a>
                    </div>
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">Contact us</h4>
                        <p class="lead mb-0">
                            TEL: 031-254-424 <BR>
                            MOB: 091/925-8585
                        </p>
                    </div>
                </div>
            </div>
    </footer>
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; <?=App::config('appName')?> 2021</small></div>
        </div>